name: backupnoti
main: com.fight.backupnoti.BackupNoti
version: 0.0.1
api-version: 1.15
description: Backup Notification For Players Made By Chinnapong Fight
commands:
  testbackup:
    description: Manually trigger shutdown warning
    usage: /testbackup